### PR TITLE
chore: switch to yarn

### PR DESCRIPTION
**Pull request by douglasduteil**

### CODE REVIEW

**Comment by revolunet** [comment]
Dockerfile please

**Comment by douglasduteil** [comment]
Oh I didn't see the Dockerfile...

**Comment by douglasduteil** [comment]
Should the image be published on the https://hub.docker.com/r/socialgouv/ ?

**Comment by revolunet** [comment]
Yes please 🙏

**Comment by douglasduteil** [comment]
Should be named socialgouv/ds-collector ?

**Comment by douglasduteil** [comment]
@revolunet I'm not sure of what to `COPY` in the image.
From local tests, only the `public`, `src`, `openapi.json` are required for `yarn start` to work

**Comment by douglasduteil** [comment]
:up: @revolunet

**Pull request merged**
